apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring
  labels:
    app.tanzu.vmware.com/workload-type: web-$SESSION_NAMESPACE
spec:
  serviceAccountName: default
  source:
    git:
      url: https://github.com/nitashav-vmw/tanzu-java-web-app-git
      ref:
        branch: master
