apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: hello-world
spec:
  tag: $REGISTRY_HOST/carto-demo/hello-world
  serviceAccountName: default
  builder:
    kind: ClusterBuilder
    name: default
  source:
    blob:
      url: ${NEW_SOURCE}
  build:
    env:
      - name: CGO_ENABLED
        value: "0"
