apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-cluster-role
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kpack.io
      - kapp.k14s.io/v1alpha1
      - kappctrl.k14s.io
      - serving.knative.dev/v1
      - carto.run
    resources:
      - gitrepositories
      - images
      - configs
      - apps
      - services
      - runnables
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get


  