apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-cluster-role-rw
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kpack.io
      - kapp.k14s.io/v1alpha1
      - kappctrl.k14s.io
      - serving.knative.dev
      - ops.tips
      - tekton.dev
      - ""
    resources:
      - gitrepositories
      - images
      - configs
      - apps
      - services
      - runnables
      - gitservers
      - configmaps
      - taskruns
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get
  - apiGroups:
      - carto.run
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-cluster-role-ro
rules:
  - apiGroups:
      - kpack.io
      - apiextensions.k8s.io
      - serving.knative.dev
      - resolution.tekton.dev
      - tekton.dev
    resources:
      - images
      - builds
      - clusterbuilders
      - routes
      - configurations
      - revisions
      - domainmappings
      - resolutionrequests
      - clustertasks
      - customresourcedefinitions
    verbs:
      - list
      - get
