#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: #@ "image-" + data.values.session_namespace
spec:
  params:
    - name: image_prefix
      default: #@ data.values.image_prefix

  imagePath: .status.latestImage

  template:
    apiVersion: kpack.io/v1alpha2
    kind: Image
    metadata:
      name: $(workload.metadata.name)$
    spec:
      tag: $(params.image_prefix)$$(workload.metadata.name)$
      serviceAccountName: default
      builder:
        kind: ClusterBuilder
        name: default
      source:
        blob:
          url: $(sources.source.url)$
      build:
        env: $(workload.spec.build.env)$
