apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: hello-world
spec:
  interval: 1m0s
  url: https://github.com/ciberkleid/hello-go
  ref:
    branch: main
  gitImplementation: libgit2
  ignore: ""
